# This will run on Travis' container-based infrastructure
sudo: false

# Only run Travis on the master branch
branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: spipack
    - DOXYFILE: $TRAVIS_BUILD_DIR/documentation
    - GH_REPO_REF: github.com/SuperParameterIzation/spipack.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - echo $TRAVIS_BUILD_DIR
     - cd build
     - cmake ..

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - pwd
  - chmod +x GenerateDocumentation.sh
  - ./GenerateDocumentation.sh
