script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - echo "HI"
     - cd build
     - cmake ..
