language: cpp
os: linux
dist: xenial

services:
  - postgresql

branches:
  only:
    - master

matrix:
    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'libpq-dev']
      env:
        - CXX=g++-7
        - CC=gcc-7

before_script:
  - cd $TRAVIS_BUILD_DIR/build
  - cmake ..

script:
  - cd $TRAVIS_BUILD_DIR/build
  - make -j5 > make_output.txt
  - cd ..
  - ./build/run-tests
