# This will run on Travis' container-based infrastructure
sudo: false

# Only run Travis on the master branch
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - cd build
     - cmake ..
     - make

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x GenerateDocumentation.sh
  - ./GenerateDocumentation.sh
