script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - echo "HI"
