
language: python
os: linux
dist: xenial
python:
  - "3.7"

services:
  - postgresql

branches:
  only:
    - master

matrix:
    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages:
            - g++-9
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz
            - python3-pip
            - python3-setuptools
      env:
        - CXX=g++-9
        - CC=gcc-9

before_script:
  - pwd $TRAVIS_BUILD_DIR
  - cd $TRAVIS_BUILD_DIR/build
  - cmake ..

script:
  - cd $TRAVIS_BUILD_DIR/build
  - make -j5
  - make -j5 examples
  - cd ..
  - ./build/run-tests

# generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR/build/
  #- make -j5 examples
  #- cmake .. -DSPIPACK_DIR=/home/install
  #- make
  #- cd ..
  - pip3 install h5py
  - pip3 install matplotlib
  - ./examples/NumericalSolvers/heat-matrix-eigenvalues/run-heat-matrix-eigenvalues
  - mkdir figures/
  - python3 _plot_result.py
  - cd $TRAVIS_BUILD_DIR/documentation
  - chmod +x GenerateDocumentation.sh
  - ./GenerateDocumentation.sh
