language: cpp
os: linux
dist: xenial

services:
  - postgresql

branches:
  only:
    - master

matrix:
    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-9', 'libpq-dev']
      env:
        - CXX=g++-9
        - CC=gcc-9

before_script:
  - cd $TRAVIS_BUILD_DIR/build
  - cmake ..

script:
  - cd $TRAVIS_BUILD_DIR/build
  - make -j5
  - cd ..
  #- ./build/run-tests
