# Check on linux and osx using gcc and clang
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - clang-8
            - boost1.67
      env:
        - MATRIX_EVAL="CC=clang-8 CXX=clang++-8"
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - boost1.67
      env:
        - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"
    - os: osx
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - clang-8
            - boost-1.67
            - hdf5
      env:
        - MATRIX_EVAL="CC=clang-8 CXX=clang++-8"
    - os: osx
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
            - boost-1.67
            - hdf5
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz
      env:
        - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"

# Only run Travis on the master branch
branches:
  only:
    - master

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - cd $TRAVIS_BUILD_DIR
     - cd build
     - cmake ..
     - make -j5
     - cd ..
     - ./build/run-tests

# Generate and deploy documentation
after_success:
  - echo $TRAVIS_BUILD_DIR
  - cd $TRAVIS_BUILD_DIR/documentation
  - pwd
  - chmod +x GenerateDocumentation.sh
  - ./GenerateDocumentation.sh
