language: generic
os: linux
dist: xenial

services:
  - postgresql

branches:
  only:
    - master

matrix:
    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-9', 'libpq-dev']
      env:
        - CXX=g++-9
        - CC=gcc-9

before_script:
  - $CXX --version
  - $CC --version
  - cd $TRAVIS_BUILD_DIR/build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug > cmake_output.txt

script:
  - $CXX --version
  - $CC --version
  - cd $TRAVIS_BUILD_DIR/build
  - make -j5 > make_output.txt
  - cd ..
  - ./build/run-tests
