language: cpp
compiler:
  - gcc-9

# Only run Travis on the master branch
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - cd $TRAVIS_BUILD_DIR
     - cd build
     - cmake .. 
     - make -j5
     - cd ..
     - ./build/run-tests

# Generate and deploy documentation
after_success:
  - echo $TRAVIS_BUILD_DIR
  - cd $TRAVIS_BUILD_DIR/documentation
  - pwd
  - chmod +x GenerateDocumentation.sh
  - ./GenerateDocumentation.sh
