// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
// ========================
//   www.exahype.eu
// ========================
#ifndef POSTPROCESSING_PlotQuantitiesOfInterest_CLASS_HEADER_
#define POSTPROCESSING_PlotQuantitiesOfInterest_CLASS_HEADER_

#include "exahype/plotters/Plotter.h"

namespace spiEX_Boltzmann {
  class BoltzmannSolver;
  class PlotQuantitiesOfInterest;
}

class spiEX_Boltzmann::PlotQuantitiesOfInterest : public exahype::plotters::Plotter::UserOnTheFlyPostProcessing {
public:
  PlotQuantitiesOfInterest(spiEX_Boltzmann::BoltzmannSolver& solver);
  virtual ~PlotQuantitiesOfInterest();

  void startPlotting(double time) override;
  void finishPlotting() override;
  void mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* const Q,
    double* const outputQuantities,
    double timeStamp) override;
};

#endif /* POSTPROCESSING_PlotQuantitiesOfInterest_CLASS_HEADER_ */
