{% set version = "latest" %}

package:
  name: muq
  version: {{ version }}

source:
  git_url: https://bitbucket.org/mituq/muq2.git
  git_depth: 1
  git_tag: conda-build

build:
  number: 0
  skip: True # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python >=3.7
    - numpy
    - h5py
    - boost-cpp ==1.74
    - eigen >=3.3
    - sundials ==5.4.0
    - nanoflann ==1.3.1
    - nlopt
  run:
    - python >=3.7
    - numpy
    - h5py
    - boost-cpp ==1.74
    - eigen >=3.3
    - sundials ==5.4.0
    - nanoflann ==1.3.1
    - nlopt

test:
  imports:
    - muq.Approximation
    - muq.Modeling
    - muq.Optimization
    - muq.SamplingAlgorithms
    - muq.Utilities

about:
  home: http://muq.mit.edu
  license: BSD-3-Clause
  summary: 'MIT Uncertainty Quantification Library (MUQ) contains a suite of uncertainty quantification tools as well as a framework for constructing complex models that blend statistical and physical components.'
