// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "BoltzmannWriter.h"

spiEX_Boltzmann::BoltzmannWriter::BoltzmannWriter(spiEX_Boltzmann::BoltzmannSolver& solver) {
  // @TODO Please insert your code here.
}

spiEX_Boltzmann::BoltzmannWriter::~BoltzmannWriter() {
}

void spiEX_Boltzmann::BoltzmannWriter::startPlotting( double time) {
  // @TODO Please insert your code here.
}


void spiEX_Boltzmann::BoltzmannWriter::finishPlotting() {
  // @TODO Please insert your code here.
}

void spiEX_Boltzmann::BoltzmannWriter::mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* const Q,
    double* const outputQuantities,
    double timeStamp
) {
  const int writtenUnknowns = 6;
  for (int i=0; i<writtenUnknowns; i++){ 
    outputQuantities[i] = Q[i];
  }
}