// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "EulerWriter.h"

Boltzmann::EulerWriter::EulerWriter(Boltzmann::BoltzmannSolver& solver) {
  // @TODO Please insert your code here.
}

Boltzmann::EulerWriter::~EulerWriter() {
}

void Boltzmann::EulerWriter::startPlotting( double time) {
  // @TODO Please insert your code here.
}


void Boltzmann::EulerWriter::finishPlotting() {
  // @TODO Please insert your code here.
}

void Boltzmann::EulerWriter::mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* const Q,
    double* const outputQuantities,
    double timeStamp
) {
  const int writtenUnknowns = 5;
  for (int i=0; i<writtenUnknowns; i++){ 
    outputQuantities[i] = Q[i];
  }
}