var searchData=
[
  ['f',['f',['../namespace__plot__result.html#acbeab8342bc7f3dcbf2a1546eac654d1',1,'_plot_result']]],
  ['fig',['fig',['../namespace__plot__result.html#a6e39593effbebea8d8ddb94eca917056',1,'_plot_result.fig()'],['../namespace__plot-results.html#a7e8b27513ce9bed09c880079947f7ef4',1,'_plot-results.fig()']]],
  ['findneighbors',['FindNeighbors',['../classspi_1_1Tools_1_1NearestNeighbors.html#ab643fc3f94a39bb0414782233d8371ac',1,'spi::Tools::NearestNeighbors::FindNeighbors(Eigen::Ref&lt; const Eigen::VectorXd &gt; const &amp;point, double const radius2, std::vector&lt; std::pair&lt; std::size_t, double &gt; &gt; &amp;neighbors, std::size_t const &amp;lag=0) const '],['../classspi_1_1Tools_1_1NearestNeighbors.html#a2dae89c063e39e6fa713c3d152dae491',1,'spi::Tools::NearestNeighbors::FindNeighbors(Eigen::Ref&lt; const Eigen::VectorXd &gt; const &amp;point, std::size_t const k, std::vector&lt; std::pair&lt; std::size_t, double &gt; &gt; &amp;neighbors, std::size_t const &amp;lag=0) const ']]],
  ['format',['format',['../namespace__plot__result.html#af8dc480c7a384a989a9b9d5b26cb4ce6',1,'_plot_result']]],
  ['ftitle',['ftitle',['../namespace__plot__result.html#a710a8107bdcf36ea821fc65a3c1b4d60',1,'_plot_result']]],
  ['functiongradient',['FunctionGradient',['../classspi_1_1NumericalSolvers_1_1KolmogorovOperator.html#aff6659e036772e8adefafcd3612fc8e8',1,'spi::NumericalSolvers::KolmogorovOperator']]],
  ['functionrepresentation',['FunctionRepresentation',['../classspi_1_1NumericalSolvers_1_1KolmogorovOperator.html#a142f7ccd0af2100fdb3f3d7ca19703b0',1,'spi::NumericalSolvers::KolmogorovOperator::FunctionRepresentation(Eigen::Ref&lt; const Eigen::VectorXd &gt; const &amp;S, Eigen::Ref&lt; const Eigen::MatrixXd &gt; const &amp;eigenvectors, std::function&lt; double(Eigen::VectorXd const &amp;)&gt; f) const '],['../classspi_1_1NumericalSolvers_1_1KolmogorovOperator.html#a8ac6196db6cb24bb018266144154e61b',1,'spi::NumericalSolvers::KolmogorovOperator::FunctionRepresentation(Eigen::Ref&lt; const Eigen::VectorXd &gt; const &amp;S, Eigen::Ref&lt; const Eigen::MatrixXd &gt; const &amp;eigenvectors, Eigen::Ref&lt; const Eigen::VectorXd &gt; const &amp;feval) const '],['../classspi_1_1NumericalSolvers_1_1KolmogorovOperator.html#a4d4bd5bb015c1c2277dd74dec30b16ee',1,'spi::NumericalSolvers::KolmogorovOperator::FunctionRepresentation(Eigen::Ref&lt; const Eigen::MatrixXd &gt; const &amp;eigenvectorsRight, std::function&lt; double(Eigen::VectorXd const &amp;)&gt; f) const '],['../classspi_1_1NumericalSolvers_1_1KolmogorovOperator.html#a61e35593e28e6cc2519271b795ad7e42',1,'spi::NumericalSolvers::KolmogorovOperator::FunctionRepresentation(Eigen::Ref&lt; const Eigen::MatrixXd &gt; const &amp;eigenvectorsRight, Eigen::Ref&lt; const Eigen::VectorXd &gt; const &amp;feval) const ']]]
];
