var searchData=
[
  ['d',['d',['../namespace__plot__result.html#ab05d0b9f4ff5f81cda9f2fa719a90775',1,'_plot_result']]],
  ['defaultparameters',['DefaultParameters',['../structspi_1_1NumericalSolvers_1_1KolmogorovOperator_1_1DefaultParameters.html',1,'spi::NumericalSolvers::KolmogorovOperator']]],
  ['defaultparameters',['DefaultParameters',['../structspi_1_1NumericalSolvers_1_1DensityEstimation_1_1DefaultParameters.html',1,'spi::NumericalSolvers::DensityEstimation']]],
  ['defaultparameters',['DefaultParameters',['../structspi_1_1NumericalSolvers_1_1SampleRepresentation_1_1DefaultParameters.html',1,'spi::NumericalSolvers::SampleRepresentation']]],
  ['defaultparameters',['DefaultParameters',['../structspi_1_1Tools_1_1NearestNeighbors_1_1DefaultParameters.html',1,'spi::Tools::NearestNeighbors']]],
  ['defaults',['defaults',['../classspi_1_1NumericalSolvers_1_1DensityEstimation.html#ab72de5af8585f1c1e07e6699bd0dbeb7',1,'spi::NumericalSolvers::DensityEstimation::defaults()'],['../classspi_1_1NumericalSolvers_1_1KolmogorovOperator.html#a3c9b1aaf24a02995693c6e21c26a3fbc',1,'spi::NumericalSolvers::KolmogorovOperator::defaults()'],['../classspi_1_1NumericalSolvers_1_1SampleRepresentation.html#a6f549b3d5ec85b5f7021eebd0e9e2c25',1,'spi::NumericalSolvers::SampleRepresentation::defaults()'],['../classspi_1_1Tools_1_1NearestNeighbors.html#a663e83d2c5e279f7c5506baf2867fbd9',1,'spi::Tools::NearestNeighbors::defaults()']]],
  ['delta',['delta',['../classspi_1_1Tools_1_1IsotropicKernel.html#a37d088c4e7d1737a762ddf841463f9b5',1,'spi::Tools::IsotropicKernel']]],
  ['dens',['dens',['../classDensityEstimationTests.html#afcd252f85ce0eb9deedf8b4a0e6f8808',1,'DensityEstimationTests']]],
  ['density',['Density',['../classspi_1_1NumericalSolvers_1_1KolmogorovOperator.html#a612816850e104d41f613dd32b5d904b7',1,'spi::NumericalSolvers::KolmogorovOperator::Density()'],['../classDensityEstimationTests.html#a04fdba86209d61314a06c207118c90f4',1,'DensityEstimationTests::density()'],['../classspi_1_1NumericalSolvers_1_1KolmogorovOperator.html#a551133fd43abff4a69e017f36529e229',1,'spi::NumericalSolvers::KolmogorovOperator::density()']]],
  ['densityestimate',['densityEstimate',['../namespace__plot__result.html#ab38249ee60261f9d6d32611915b369b1',1,'_plot_result']]],
  ['densityestimation',['DensityEstimation',['../classspi_1_1NumericalSolvers_1_1DensityEstimation.html#ab1d4fb4d5bed3557e6bf355dbdbb2406',1,'spi::NumericalSolvers::DensityEstimation::DensityEstimation(std::shared_ptr&lt; muq::Modeling::RandomVariable &gt; const &amp;rv, YAML::Node const &amp;options)'],['../classspi_1_1NumericalSolvers_1_1DensityEstimation.html#aabbfc478c558693fd2cd56dbc7cc5da1',1,'spi::NumericalSolvers::DensityEstimation::DensityEstimation(std::shared_ptr&lt; muq::SamplingAlgorithms::SampleCollection &gt; const &amp;samples, YAML::Node const &amp;options)'],['../classspi_1_1NumericalSolvers_1_1DensityEstimation.html#a9de8ab325ca77a988c04833d7bfd53a0',1,'spi::NumericalSolvers::DensityEstimation::DensityEstimation(std::shared_ptr&lt; const spi::Tools::NearestNeighbors &gt; const &amp;samples, YAML::Node const &amp;options)']]],
  ['densityestimation',['DensityEstimation',['../classspi_1_1NumericalSolvers_1_1DensityEstimation.html',1,'spi::NumericalSolvers']]],
  ['densityestimation_2ecpp',['DensityEstimation.cpp',['../DensityEstimation_8cpp.html',1,'']]],
  ['densityestimation_2ehpp',['DensityEstimation.hpp',['../DensityEstimation_8hpp.html',1,'']]],
  ['densityestimationtests',['DensityEstimationTests',['../classDensityEstimationTests.html',1,'']]],
  ['densityestimationtests_2ecpp',['DensityEstimationTests.cpp',['../DensityEstimationTests_8cpp.html',1,'']]],
  ['descending',['Descending',['../classspi_1_1Tools_1_1SortVector.html#a9931062c28aeba2d5316e869c3e037fd',1,'spi::Tools::SortVector']]],
  ['description_2emd',['description.md',['../Kolmogorov-eigendecomposition_2description_8md.html',1,'']]],
  ['description_2emd',['description.md',['../Kolmogorov-inverse_2description_8md.html',1,'']]],
  ['description_2emd',['description.md',['../density-estimation_2description_8md.html',1,'']]],
  ['dim',['dim',['../classDensityEstimationTests.html#a5e2edfde9e13c7b07fae0718261472b3',1,'DensityEstimationTests::dim()'],['../classKolmogorovOperatorTests.html#a165494fd97633601455a66f8277cdbdd',1,'KolmogorovOperatorTests::dim()'],['../classSampleRepresentationTests.html#a9072d9f0949b56162dc29ad4173018c4',1,'SampleRepresentationTests::dim()'],['../classNearestNeighborsTests.html#aa16fc1b3af0a381cba6c8e1ac4eaf3f6',1,'NearestNeighborsTests::dim()']]],
  ['dist',['dist',['../namespace__plot__result.html#a7db8ea5f24d4701c0ec6a51cd1aa3375',1,'_plot_result']]],
  ['description',['description',['../md__home_travis_build_SuperParameterIzation_spipack_examples_NumericalSolvers_density-estimation_description.html',1,'']]],
  ['description',['description',['../md__home_travis_build_SuperParameterIzation_spipack_examples_NumericalSolvers_Kolmogorov-eigendecomposition_description.html',1,'']]],
  ['description',['description',['../md__home_travis_build_SuperParameterIzation_spipack_examples_NumericalSolvers_Kolmogorov-inverse_description.html',1,'']]]
];
